# copy_text.py — every word on the page, English and Thai, written by hand.

NAV = ["book", "map", "owners", "date", "glyphs", "count", "grammar", "repeats", "cipher", "hoax", "language", "pictures", "claims"]

SECTIONS_EN = {"H": "Herbal", "A": "Astronomical", "Z": "Zodiac", "B": "Bathing women", "C": "Rosettes and circles", "P": "Pharmaceutical", "S": "Stars, text only", "T": "Text only"}
SECTIONS_TH = {"H": "สมุนไพร", "A": "ดาราศาสตร์", "Z": "จักรราศี", "B": "หญิงในอ่างน้ำ", "C": "วงกลมและดอกกุหลาบ", "P": "ตำรายา", "S": "ดาว ข้อความล้วน", "T": "ข้อความล้วน"}

# claims: year, who, what, a line on how it was received; status out | open | method
CLAIMS = [
    {"year": "1921", "who": "William Romaine Newbold", "status": "out",
     "what_en": "Roger Bacon, in microscopic shorthand", "what_th": "โรเจอร์ เบคอน เขียนชวเลขขนาดจิ๋ว",
     "note_en": "He read tiny strokes inside the letters as Greek shorthand and found Bacon describing a telescope and cells. John Manly showed in 1931 that the strokes are cracks in drying ink, and that Newbold's method could turn any text into any message.",
     "note_th": "เขาอ่านขีดเล็ก ๆ ในตัวอักษรเป็นชวเลขกรีก และพบเบคอนเล่าเรื่องกล้องส่องทางไกลและเซลล์ จอห์น แมนลีย์ แสดงในปี 1931 ว่าขีดพวกนั้นคือรอยแตกของหมึกที่แห้ง และวิธีของนิวโบลด์เปลี่ยนข้อความใดเป็นข้อความใดก็ได้"},
    {"year": "1944", "who": "William Friedman", "status": "open",
     "what_en": "A made-up language, built on a plan", "what_th": "ภาษาที่สร้างขึ้นตามแบบแผน",
     "note_en": "The codebreaker who broke Japan's Purple machine ran two study groups on the manuscript. He came to think it was an early artificial language, its words built from a classification of things, and he hid that belief in an anagram.",
     "note_th": "นักถอดรหัสผู้ไขเครื่อง Purple ของญี่ปุ่น ตั้งกลุ่มศึกษาต้นฉบับนี้สองครั้ง เขาเชื่อว่ามันเป็นภาษาประดิษฐ์ยุคแรก คำสร้างจากการจัดหมวดหมู่สิ่งของ และซ่อนความเชื่อนั้นไว้ในคำสลับอักษร"},
    {"year": "1945", "who": "Leonell Strong", "status": "out",
     "what_en": "Anthony Ascham, an English herbalist, in cipher", "what_th": "แอนโทนี แอสคัม หมอสมุนไพรอังกฤษ เข้ารหัสไว้",
     "note_en": "A cancer researcher who said he had found a double-key cipher hiding sixteenth-century English. Nobody could repeat his steps, and the vellum turned out a century older than Ascham.",
     "note_th": "นักวิจัยมะเร็งที่บอกว่าพบรหัสสองกุญแจซ่อนภาษาอังกฤษศตวรรษที่ 16 ไม่มีใครทำซ้ำขั้นตอนของเขาได้ และแผ่นหนังเก่ากว่าแอสคัมร้อยปี"},
    {"year": "1978", "who": "John Stojko", "status": "out",
     "what_en": "Ukrainian with the vowels left out", "what_th": "ภาษายูเครนที่ตัดสระออก",
     "note_en": "His readings did not hang together as Ukrainian of any period.",
     "note_th": "คำอ่านของเขาไม่เป็นภาษายูเครนยุคใดเลย"},
    {"year": "1987", "who": "Leo Levitov", "status": "out",
     "what_en": "Cathar rites, in a mix of Flemish and other tongues", "what_th": "พิธีของพวกคาธาร์ ในภาษาเฟลมิชปนภาษาอื่น",
     "note_en": "Historians of the Cathars found his account of their beliefs wrong, and the language he described has no other record.",
     "note_th": "นักประวัติศาสตร์เรื่องคาธาร์ชี้ว่าเขาเล่าความเชื่อของพวกนั้นผิด และภาษาที่เขาบรรยายไม่มีหลักฐานที่อื่น"},
    {"year": "2004", "who": "Gordon Rugg", "status": "method",
     "what_en": "A hoax, made with a table and a card with holes", "what_th": "ของปลอม ทำด้วยตารางกับแผ่นเจาะรู",
     "note_en": "He did not translate it. He showed that a sixteenth-century tool could turn out text with many of its odd habits. Try it in Hoax below.",
     "note_th": "เขาไม่ได้แปล เขาแสดงว่าเครื่องมือศตวรรษที่ 16 ผลิตข้อความที่มีนิสัยแปลก ๆ หลายอย่างแบบเดียวกันได้ ลองเล่นได้ที่หัวข้อของปลอมด้านล่าง"},
    {"year": "2013", "who": "Arthur Tucker & Rexford Talbert", "status": "out",
     "what_en": "Plants of Mexico, words in Nahuatl", "what_th": "พืชของเม็กซิโก คำในภาษานาวัตล์",
     "note_en": "They matched drawings to American plants. The vellum dates from before Columbus sailed, so most readers set it aside.",
     "note_th": "พวกเขาจับคู่ภาพกับพืชในทวีปอเมริกา แต่แผ่นหนังเก่ากว่าการเดินเรือของโคลัมบัส คนส่วนใหญ่จึงไม่รับ"},
    {"year": "2014", "who": "Stephen Bax", "status": "open",
     "what_en": "A few plant and star names, letter by letter", "what_th": "ชื่อพืชและดาวไม่กี่คำ ทีละตัวอักษร",
     "note_en": "A linguist who matched labels next to pictures with names, such as Taurus beside a cluster of stars and kantairon, centaury, beside a plant, and offered sound values for some letters. He called it provisional. Others could not extend it to whole lines.",
     "note_th": "นักภาษาศาสตร์ผู้จับคู่ป้ายข้างภาพกับชื่อ เช่น Taurus ข้างกระจุกดาว และ kantairon พืชตระกูลเซนทอรีข้างภาพต้นไม้ และเสนอเสียงให้อักษรบางตัว เขาเรียกมันว่าข้อเสนอชั่วคราว คนอื่นต่อยอดไปเป็นบรรทัดเต็มไม่ได้"},
    {"year": "2016", "who": "Greg Kondrak & Bradley Hauer", "status": "out",
     "what_en": "Hebrew, with the letters of each word shuffled", "what_th": "ภาษาฮีบรู สลับตัวอักษรในแต่ละคำ",
     "note_en": "A computer compared the text with 380 languages and picked Hebrew. Run through Google Translate, their first line read as a garbled sentence about a priest and a house. Hebrew scholars found no Hebrew in it.",
     "note_th": "คอมพิวเตอร์เทียบข้อความกับ 380 ภาษาแล้วเลือกฮีบรู เมื่อใส่ Google Translate บรรทัดแรกออกมาเป็นประโยคสับสนเรื่องนักบวชกับบ้าน ผู้รู้ภาษาฮีบรูไม่พบภาษาฮีบรูในนั้น"},
    {"year": "2017", "who": "Nicholas Gibbs", "status": "out",
     "what_en": "Latin abbreviations, a women's health manual", "what_th": "คำย่อภาษาละติน คู่มือสุขภาพสตรี",
     "note_en": "Printed in the Times Literary Supplement. Lisa Fagin Davis and others answered that his sample sentences were not grammatical Latin.",
     "note_th": "ตีพิมพ์ใน Times Literary Supplement ลิซา เฟกิน เดวิส และคนอื่นตอบว่าประโยคตัวอย่างของเขาไม่ใช่ละตินที่ถูกไวยากรณ์"},
    {"year": "2019", "who": "Gerard Cheshire", "status": "out",
     "what_en": "Proto-Romance, written for a queen", "what_th": "ภาษาโรมานซ์ยุคต้น เขียนถวายพระราชินี",
     "note_en": "Published in a journal and announced by his university, which took down its news story after medieval scholars objected that the language he described never existed.",
     "note_th": "ตีพิมพ์ในวารสารและมหาวิทยาลัยประกาศข่าว แล้วถอนข่าวออกเมื่อนักวิชาการยุคกลางค้านว่าภาษาที่เขาบรรยายไม่เคยมีอยู่"},
    {"year": "2020", "who": "Torsten Timm & Andreas Schinner", "status": "method",
     "what_en": "Meaningless text, each word copied from one above and changed", "what_th": "ข้อความไร้ความหมาย แต่ละคำลอกจากคำข้างบนแล้วแก้นิดหน่อย",
     "note_en": "A model of how a scribe could have produced the text without a message. It explains the near-repeats you can see in Repeats.",
     "note_th": "แบบจำลองว่าผู้คัดลอกอาจเขียนข้อความทั้งเล่มโดยไม่มีสารอะไรเลย อธิบายคำซ้ำแบบเกือบเหมือนที่เห็นในหัวข้อคำซ้ำ"},
    {"year": "2024", "who": "Keagan Brewer & Michelle Lewis", "status": "open",
     "what_en": "Sex and childbirth, kept secret on purpose", "what_th": "เรื่องเพศและการคลอด ปิดไว้โดยตั้งใจ",
     "note_en": "Two historians who read the pictures, not the words. They tie the book to the physician Johannes Hartlieb, who urged 'secret letters' for recipes about contraception and abortion, and read the Rosettes as conception. A hypothesis, not a reading.",
     "note_th": "นักประวัติศาสตร์สองคนที่อ่านภาพ ไม่ใช่คำ พวกเขาโยงหนังสือกับแพทย์โยฮันเนส ฮาร์ทลีบ ผู้แนะให้ใช้ 'อักษรลับ' กับตำราคุมกำเนิดและทำแท้ง และอ่านหน้าวงกลมใหญ่ว่าเป็นการปฏิสนธิ เป็นสมมติฐาน ไม่ใช่การอ่าน"},
    {"year": "2025", "who": "Michael Greshko", "status": "method",
     "what_en": "A cipher of dice and cards that makes Voynich-like text", "what_th": "รหัสจากลูกเต๋ากับไพ่ ที่ได้ข้อความคล้ายวอยนิช",
     "note_en": "He built a cipher from tools a fifteenth-century Italian could have owned and showed that it turns Latin or Italian into text with many Voynich fingerprints. He calls it almost certainly not the way the manuscript was made, and it decrypts none of its text.",
     "note_th": "เขาสร้างรหัสจากเครื่องมือที่ชาวอิตาลีศตวรรษที่ 15 มีได้ และแสดงว่ามันเปลี่ยนละตินหรืออิตาลีเป็นข้อความที่มีลายนิ้วมือแบบวอยนิชหลายอย่าง เขาบอกว่าแทบแน่นอนว่าไม่ใช่วิธีที่ต้นฉบับถูกทำ และมันไม่ได้ถอดข้อความใดของต้นฉบับ"},
]

UI = {
    "en": {
        "title": "The Voynich Manuscript",
        "short": "Voynich",
        "other_title": "ข้อเขียนวอยนิช",
        "desc": "How people try to read the Voynich manuscript, a fifteenth-century book in a script nobody can read: the book, its owners, its date, and the tests people run on its text, with live toys for transcription, word counts, word grammar, repeats, ciphers and hoaxes. In English and Thai.",
        "card_alt": "A drawn page of Voynich script beside a painted plant, with the title The Voynich Manuscript",
        "hero_alt": "A page in the style of the manuscript: a plant with roots and leaves, and lines of Voynich script written stroke by stroke from a real page",
        "kicker": "A book nobody can read",
        "lede": "Six hundred years old, 240 pages, an alphabet found nowhere else. Here is how people try to make sense of it, and what each try turns up.",
        "hero_go": "Run the tests",
        "cardline": "how people try to read it",
        "nav_label": "Sections",
        "nav": ["Book", "Map", "Owners", "Date", "Glyphs", "Count", "Grammar", "Repeats", "Cipher", "Hoax", "Language", "Pictures", "Claims"],
        "lang_this": "EN",
        "lang_other": ("th/", "ไทย", "th"),

        "book_kick": "Beinecke MS 408",
        "book_h": "The book",
        "book_p": [
            "The Voynich manuscript is a small book of calfskin vellum, about 23 by 16 centimetres, now at Yale's Beinecke Rare Book and Manuscript Library. About 240 pages survive; some fold out to several times the page size. It has 102 leaves; the old leaf numbers run to 116, so 14 are missing.",
            "Every page is written in an alphabet of about twenty to thirty letters that turns up in no other document. The writing flows like a practised hand, with no crossings-out. Around it are pictures: plants that match no plant anyone agrees on, star charts, the zodiac, naked women in green pools joined by pipes, a huge foldout of circles, and jars beside roots and leaves.",
            "In the hero drawing at the top, the letters are copied from a real herbal page, stroke by stroke, and the plant is drawn by a rule with a dice roll. Tap it for another page.",
        ],

        "map_kick": "227 pages with text",
        "map_h": "Map of the book",
        "map_p": [
            "Each tile is a page with writing, in book order. The bar shows how much text it holds. Colour it by the kind of picture, by the two dialects Prescott Currier found in 1976, or by the five scribes Lisa Fagin Davis found in 2020. The dialects and the scribes line up with the sections: whoever made the book did not write it all the same way.",
        ],
        "map_modes": ["Section", "Currier language", "Scribe"],
        "map_page": "The first lines of the chosen page, drawn",
        "map_note": "Tap a tile to see its first lines. Folio numbers name a leaf and its side: f1r is the front of leaf 1, f1v the back. Section, language and scribe come from the page headers of René Zandbergen's transliteration.",

        "own_kick": "Provenance",
        "own_h": "Owners",
        "own_p": [
            "The book's story starts in Prague around 1600 and comes to us through a run of letters, a signature and a sale.",
        ],
        "hist": [
            ("1599?", "Marci's letter says the Holy Roman Emperor Rudolf II paid 600 ducats for it. In 2022 Stefan Guzy found Rudolf buying books from Karl Widemann in 1599 for 600 florins, probably this sale. Rudolf collected curiosities and alchemists."),
            ("1608+", "Jacobus Horčický de Tepenec, Rudolf's chemist, writes his name at the foot of the first page. He took the 'de Tepenec' title in 1608, so he signed after that. The name had faded away; Voynich brought it back with chemicals around 1914, and it reads under ultraviolet light."),
            ("1639", "Georg Baresch, an alchemist in Prague, writes to the Jesuit scholar Athanasius Kircher in Rome, who claimed to have read Egyptian hieroglyphs, and asks for help. His letter is the earliest sure mention of the book."),
            ("1665", "Johannes Marcus Marci, rector of the University of Prague, inherits the book and posts it to Kircher with a letter. The letter is still with the book. Marci probably wrote the erased alphabets in the margin of the first page, the earliest known try at a key."),
            ("1912", "Wilfrid Voynich, a rare-book dealer, buys it from the Jesuits near Rome, with a crate of other books, and spends the rest of his life trying to get it read."),
            ("1961", "After Voynich dies in 1930 and his widow Ethel in 1960, their heir Anne Nill sells it to the dealer Hans P. Kraus for $24,500. Kraus finds no buyer."),
            ("1969", "Kraus gives it to Yale. The Beinecke Library puts every page online, free to look at."),
        ],

        "date_kick": "Radiocarbon",
        "date_h": "Who could have written it?",
        "date_p": [
            "In 2009 a team at the University of Arizona cut four tiny samples from four leaves and dated the carbon in them. The calves died between 1404 and 1438. A chemical study of the inks and paints found them consistent with that age, though ink cannot be dated as closely as vellum.",
            "Vellum could sit blank on a shelf for years before someone wrote on it. Slide the shelf time and watch which suspects become possible. Roger Bacon, the favourite for decades, died more than a century before the calves were born.",
        ],
        "d_wait": "Years the blank vellum waited",
        "years": "years",
        "vellum_band": "vellum 1404–1438",
        "date_note": "Green means the person was alive while the vellum was fresh enough to use. A forger working with old blank vellum would need a great deal of it: about 240 matching pages. Lifespans are rounded.",

        "gl_kick": "Step one: write it down",
        "gl_h": "Glyphs",
        "gl_p": [
            "Counting starts with deciding what the letters are. Is that a curl or a new letter? Are two loops joined at the top one letter or two? Different readers answered differently, and their counts came out different.",
            "Most work today uses EVA, the European Voynich Alphabet, set up by René Zandbergen and Gabriel Landini in 1997–98. EVA gives each pen stroke group a Latin letter so a computer can store it. EVA letters are labels, not sounds: <i>daiin</i> is how we spell a word on a keyboard, not how anyone said it.",
            "Tap a glyph. The bars show where it sits in a word. Some letters keep to one place, the way English <i>q</i> keeps before <i>u</i>.",
        ],
        "g_where": "Where the glyph stands in a word",
        "count_h": "One letter or two?",
        "count_p": [
            "EVA writes the bench-shaped glyph as <i>ch</i>, two letters. Count it as one glyph and the numbers move. The second-order entropy, h2, measures how well one letter predicts the next; the next section explains it.",
        ],
        "u_eva": "Count EVA letters", "u_glyph": "Count ch, sh, ckh as one glyph",
        "u_letters": "Different letters", "u_len": "Letters per word",
        "name_h": "Your name in Voynich letters",
        "name_p": "Type a name. Each Latin letter becomes a Voynich glyph by a table we made up for the cipher toy further down. It is a costume, not a translation.",
        "name_default": "Annika",

        "cnt_kick": "Step two: count",
        "cnt_h": "Count it",
        "cnt_p": [
            "If you cannot read a text you can still measure it. People run the same tests on the manuscript that they run on known languages, then look for where it matches and where it breaks. Below, 12,000 words of each: the manuscript's two dialects, Latin from Augustine's <i>Confessions</i>, English from Culpeper's <i>Herbal</i> of 1652, and random letters. The cipher and hoax toys further down add their own.",
        ],
        "b_zipf": "Word frequency (Zipf)",
        "b_zipf_note": "Rank each word by how often it appears and plot both on log scales. In human languages the line falls with a slope near −1, dashed. The manuscript follows it. Random letters do not.",
        "b_len": "Word length",
        "b_len_note": "The manuscript's word lengths bunch tightly around five letters, with few very short or very long words. Latin and English spread wider.",
        "b_h2": "h2: how much the next letter surprises you",
        "b_h2_note": "Measured in bits. The lower it is, the easier you can guess the next letter from the one before. European languages sit near 3. The manuscript sits near 2: its letters follow each other in a narrow set of habits.",
        "b_rep_h": "Same word twice in a row",
        "b_rep_note": "Per thousand words. Latin and English rarely repeat a word straight away. The manuscript does it about ten times as often, and sometimes three times running.",
        "b_rank": "rank", "b_count": "times seen", "b_letters": "letters in the word", "b_share": "share of words",
        "b_types": "Different words", "b_mean": "Letters per word", "b_rep": "Repeats per 1,000", "b_top": "Commonest words",
        "cnt_after": [
            "So the text follows Zipf's law like a language, but its letters are far more predictable than any European language, and it repeats itself in ways sentences rarely do. Each camp below starts from those two facts.",
            "Other measures point the same way. Marcelo Montemurro and Damián Zanette found in 2013 that some words cluster in particular sections, the way topic words do in known texts. Others answer that a system for making meaningless text could produce clusters too.",
        ],

        "gr_kick": "Step three: take words apart",
        "gr_h": "Word grammar",
        "gr_p": [
            "Voynich words are built from pieces that come in a fixed order. <i>q</i> comes first if it comes at all; tall 'gallows' letters come near the front; <i>dy</i>, <i>aiin</i> and <i>ol</i> come last. Jorge Stolfi in the 1990s and others since have drawn this up as a grammar of slots.",
            "Ours below has eleven slots. Spin it to make a word, or type one to see it parsed. The share of the manuscript's words that fit is measured live.",
        ],
        "gr_spin": "Spin", "gr_try": "Type a word in EVA",
        "gr_found": "in the manuscript {n} times", "gr_new": "not in the manuscript", "gr_nofit": "does not fit the slots",
        "gr_tok_l": "Words in the text that fit", "gr_ty_l": "Different words that fit",
        "gr_note": "Languages have word structure too, but it is looser: English allows <i>strengths</i> and <i>a</i>. A slot grammar this tight is one reason many think the words are generated by a system, whether a cipher, a made-up language or a hoax.",

        "rp_kick": "Step four: read it like a scribe",
        "rp_h": "Repeats",
        "rp_p": [
            "Pick a page. Words that already appeared on the page are red. Words one glyph away from an earlier word, such as <i>qokedy</i> after <i>qokeedy</i> or <i>okedy</i>, are yellow.",
            "Torsten Timm noticed how many words are near-copies of words just above them, and with Andreas Schinner built a model in 2020: the scribe made up nothing new, but copied a word from earlier on the page and changed a letter or two. Try it in Hoax.",
        ],
        "rp_pick": "Page",
        "rp_same": "Seen earlier on the page", "rp_near": "One glyph off", "rp_new": "New",
        "rp_note": "Ordinary text repeats too: <i>the</i>, <i>and</i>, <i>et</i>. Compare the share of yellow words, near-misses, which ordinary languages produce far less often.",

        "ci_kick": "Theory one",
        "ci_h": "A cipher",
        "ci_p": [
            "Maybe the book says something ordinary, in Latin or Italian or German, hidden by a cipher. Early-fifteenth-century Italy had ciphers that swapped letters for symbols and added symbols that meant nothing. The codebreakers of both world wars tried every method they knew and none of them worked.",
            "Type some Latin and choose a method. The bench in Count shows what each one does to the statistics, on 12,000 words of Augustine.",
        ],
        "c_plain": "Plain text (Latin works best)",
        "c_default": "herba haec nascitur in locis humidis et habet folia lata et radicem longam",
        "c_sub": "Swap each letter", "c_verb": "Spell each letter as a syllable",
        "ci_how": [
            "<b>Swap</b>: each letter becomes one Voynich glyph. Words keep their lengths and their pattern; h2 stays near Latin's.",
            "<b>Syllable</b>: a verbose cipher. Each letter becomes a short chunk such as <i>ok</i> or <i>aiin</i>, and the chunks are cut into new words. h2 drops toward the manuscript's, but the vocabulary shrinks.",
        ],
        "c_bench": "On 12,000 words of Augustine",
        "ci_after": [
            "Swapping letters cannot explain the low h2: a plain swap keeps the language's own patterns, which Friedman's teams noticed. A verbose cipher gets closer. In 2025 Michael Greshko built one from dice and playing cards, tools a fifteenth-century Italian could have owned, and showed it can match many of the manuscript's statistics. Nobody has found the cipher that turns its text back into a language.",
        ],

        "hx_kick": "Theory two",
        "hx_h": "A hoax",
        "hx_p": [
            "Maybe there is no message: someone made a strange book to sell. Wilfrid Voynich himself was once suspected, but the vellum, the ink and the 1665 letter rule him out. Edward Kelley, a con man at Rudolf's court, was a favourite. The question became whether anyone in that age could produce 240 pages of text this regular without meaning anything.",
            "In 2004 Gordon Rugg showed one way. Fill a table with word pieces: starts, middles, ends. Lay a card with three holes over it. Each place you set the card gives you a word. Slide it and keep going.",
        ],
        "hx_grille": "Rugg's grille: a table of word pieces, with the holes of the card in gold",
        "hx_word": "Through the holes:",
        "hx_step": "Slide the card", "hx_card": "Another card", "hx_new": "New table", "hx_run": "Make 12,000 words for the bench",
        "hx_grille_p": [
            "Our table is small and its pieces are ours, not Rugg's. His point holds: words from a grille have the manuscript's tight structure and low h2. With a small table the vocabulary comes out too small and Zipf's line fails; Rugg used larger tables and more cards.",
        ],
        "gr_ran": "Added to the bench: {types} different words, h2 {h2}, Zipf slope {z}.",
        "sc_h": "Self-citation",
        "sc_p": [
            "Timm and Schinner's scribe starts with one line from the manuscript, then writes each new word by copying a word from the line above or nearby and changing it a little: <i>k</i> for <i>t</i>, an extra <i>e</i>, a new ending. The newest word is red; the dashed line points to the word it most resembles.",
        ],
        "sc_play": "Write a new page",
        "sc_after": [
            "Ours is a rough sketch of their method and its numbers drift from the manuscript's; theirs is tuned and matches more of them. Neither a grille nor copying proves the text is meaningless. They show that a lack of meaning would explain the statistics as well as a cipher would.",
        ],

        "lg_kick": "Theory three",
        "lg_h": "A language",
        "lg_p": [
            "Maybe it is a real language written in a new alphabet: a lost dialect, a language from far away written down by a traveller, or a language with words cut short so that endings repeat. Zipf's law, the clusters of section words, and the way labels next to pictures differ from running text all fit a language.",
            "The low h2 is the problem. It fits a language only if the alphabet works differently from ours, for example if some glyphs are parts of letters, or if <i>aiin</i> is a single sound written with four strokes. EVA's choice of what counts as a letter matters here, as you saw in Glyphs.",
            "Every claimed reading so far has failed one of two tests: the method must produce the same answer for anyone who follows it, and it must read whole lines into grammatical sentences. Partial readings of a few labels, like Stephen Bax's, pass the first test for a few words and have not yet reached the second.",
            "In 2026 Colin Layfield and Lisa Fagin Davis ran latent semantic analysis, a test of whether neighbouring passages share vocabulary the way topics do, and found the text flows like known texts. In a second paper they argue the book began as loose folded sheets, read in order and later bound out of order, and try to put them back.",
        ],

        "pc_kick": "Reading without words",
        "pc_h": "Pictures",
        "pc_p": [
            "The pictures are the one part anyone can look at. Botanists have tried to name the plants for a century; some look like violets, ferns, water lilies or a sunflower, and many look like nothing at all, sometimes combining the roots of one plant with the leaves of another.",
            "Ten of the zodiac pages have month names beside them, March to December, written in Latin letters by a later hand: <i>mars</i>, <i>aberil</i>, <i>may</i>, <i>augst</i>. They are among the few words in the book anyone can read. René Zandbergen reads them as northern French, close to the month names on an astrolabe from Picardy, so someone there may once have held it.",
        ],
        "pc_after": [
            "In 2024 Keagan Brewer and Michelle Lewis read the women, pools and turning diagrams as fifteenth-century medicine about sex and childbirth, which writers of the time sometimes hid in cipher. Like every reading of the pictures, it says what the book may be about without reading a word of it.",
        ],

        "cl_kick": "A century of answers",
        "cl_h": "Claims",
        "cl_p": [
            "Someone announces a solution most years. Here are the ones that drew the most notice. Red bar: rejected by specialists. Yellow: still argued over. Green: a method that makes Voynich-like text, not a translation.",
        ],
        "cl_after": [
            "The Beinecke receives claimed solutions by email so often that its curators have a reply ready. Lisa Fagin Davis, who has read many of them, asks two things of each: does it read whole sentences, and would someone else following the same rules get the same words?",
        ],

        "words_h": "Words",
        "src_h": "Sources",
        "src_p": ["The transliteration on this page is René Zandbergen's ZL file, version 3b, from voynich.nu, offered under CC0. Latin and English samples come from Project Gutenberg. Every number on the page is computed in your browser from those files."],
        "foot": "Text CC BY 4.0, NaNoBotCo. Code MIT. Pictures from Wikimedia Commons, credited under each.",
        "pic": {
            "f1r": "f1r, the first page, with its faded signature at the foot",
            "herbal": "f2r, a herbal page: one plant, roots to flower, wrapped in text. Bax read its label as centaury",
            "rosettes": "Part of the Rosettes foldout (f85v–f86r), nine circles joined by causeways",
            "f116v": "f116v, the last page: a few lines mixing Latin-looking words, German and Voynich letters, the most argued-over text in the book",
            "voynich": "Wilfrid Voynich among his books in his Soho Square shop, London",
            "zodiac": "f70v2, Pisces, with the month name <i>mars</i> in Latin letters",
            "balneo": "f75r: women in pools joined by pipes",
            "pharma": "f99r: jars, roots and leaves with labels",
        },
        "js": {
            "sections": SECTIONS_EN,
            "words_unit": "words", "lang_a": "Language A", "lang_b": "Language B", "unknown": "unassigned", "hand": "Scribe",
            "years": "years", "vellum_band": "vellum 1404–1438",
            "cands": [["Roger Bacon", 1219, 1292], ["Leon Battista Alberti", 1404, 1472], ["Johannes Hartlieb", 1410, 1468], ["Antonio Averlino", 1400, 1469], ["John Dee", 1527, 1609], ["Edward Kelley", 1555, 1597], ["Rudolf II", 1552, 1612], ["Wilfrid Voynich", 1865, 1930]],
            "g_pos": ["first", "middle", "last"],
            "g_note": {
                "q": "<i>q</i> nearly always opens a word and is nearly always followed by <i>o</i>: <i>qo</i>, as in <i>qokeedy</i>.",
                "k": "<i>k</i>, <i>t</i>, <i>p</i> and <i>f</i> are the tall 'gallows' letters. <i>p</i> and <i>f</i> cluster in the first line of a paragraph.",
                "t": "A gallows letter. Bench gallows such as <i>cth</i> stand one over a bench <i>ch</i>.",
                "p": "A gallows letter with a long top stroke, common on the first line of a paragraph.",
                "f": "The rarest gallows letter, mostly on first lines.",
                "n": "Almost always at the end of a word, after a run of <i>i</i>: <i>aiin</i>, <i>daiin</i>.",
                "m": "Almost always at the end, and often at the end of a line.",
                "i": "Comes in runs of one to three, then <i>n</i> or <i>r</i>: <i>ain</i>, <i>aiin</i>, <i>aiiin</i>.",
                "y": "Mostly at the end of a word: <i>dy</i>, <i>chy</i>, <i>qokeedy</i>.",
                "ch": "The 'bench'. EVA writes it as two letters, but the pen makes one shape.",
                "o": "The commonest glyph, found anywhere in a word.",
                "e": "Often doubled or tripled: <i>chee</i>, <i>qokeeey</i>.",
                "d": "Often before <i>y</i> or <i>aiin</i>: <i>dy</i>, <i>daiin</i>, the commonest word.",
            },
            "corp": {"va": "Voynich A", "vb": "Voynich B", "la": "Latin", "en": "English", "sub": "Latin, letters swapped", "verb": "Latin, syllable cipher", "gr": "Grille", "sc": "Self-citation", "rnd": "Random letters"},
            "b_rank": "rank (log)", "b_count": "times seen (log)", "b_letters": "letters in the word", "b_share": "share of words",
            "b_types": "Different words", "b_mean": "Letters per word", "b_rep": "Repeats per 1,000", "b_top": "Commonest words",
            "gr_found": "in the manuscript {n} times", "gr_new": "not in the manuscript", "gr_nofit": "does not fit the slots",
            "gr_ran": "Added to the bench: {types} different words, h2 {h2}, Zipf slope {z}.",
        },
    },
    "th": {
        "title": "ข้อเขียนวอยนิช",
        "short": "วอยนิช",
        "other_title": "The Voynich Manuscript",
        "desc": "คนพยายามอ่านต้นฉบับวอยนิชอย่างไร หนังสือศตวรรษที่ 15 ในอักษรที่ไม่มีใครอ่านออก ตัวหนังสือ เจ้าของ อายุ และการทดสอบที่คนใช้กับข้อความ พร้อมของเล่นสด การถอดอักษร นับคำ ไวยากรณ์คำ คำซ้ำ รหัส และของปลอม ภาษาไทยและอังกฤษ",
        "card_alt": "หน้าอักษรวอยนิชวาดข้างภาพพืชระบายสี พร้อมชื่อ ต้นฉบับวอยนิช",
        "hero_alt": "หน้ากระดาษแบบต้นฉบับ พืชมีรากและใบ กับบรรทัดอักษรวอยนิชที่เขียนทีละเส้นจากหน้าจริง",
        "kicker": "หนังสือที่ไม่มีใครอ่านออก",
        "lede": "อายุหกร้อยปี 240 หน้า อักษรที่ไม่พบที่ไหนอีก นี่คือวิธีที่คนพยายามทำความเข้าใจ และแต่ละวิธีเจออะไร",
        "hero_go": "ลองทดสอบ",
        "cardline": "คนพยายามอ่านมันอย่างไร",
        "nav_label": "หัวข้อ",
        "nav": ["ตัวเล่ม", "แผนที่", "เจ้าของ", "อายุ", "อักษร", "นับ", "ไวยากรณ์", "คำซ้ำ", "รหัส", "ของปลอม", "ภาษา", "ภาพ", "คำตอบ"],
        "lang_this": "ไทย",
        "lang_other": ("../", "EN", "en"),

        "book_kick": "Beinecke MS 408",
        "book_h": "ตัวเล่ม",
        "book_p": [
            "ต้นฉบับวอยนิชเป็นหนังสือเล่มเล็กทำจากหนังลูกวัว ขนาดราว 23 คูณ 16 เซนติเมตร เก็บอยู่ที่ห้องสมุดหนังสือหายากไบเนคกีของมหาวิทยาลัยเยล เหลือราว 240 หน้า บางหน้าพับออกได้กว้างหลายเท่าของหน้าปกติ มี 102 แผ่น เลขแผ่นเดิมไปถึง 116 จึงหายไป 14 แผ่น",
            "ทุกหน้าเขียนด้วยอักษรราวยี่สิบถึงสามสิบตัวที่ไม่ปรากฏในเอกสารอื่นใด ลายมือลื่นไหลเหมือนคนเขียนคล่อง ไม่มีการขีดฆ่า รอบ ๆ มีภาพ พืชที่ไม่มีใครตกลงได้ว่าเป็นพืชอะไร แผนที่ดาว จักรราศี หญิงเปลือยในบ่อสีเขียวที่ต่อกันด้วยท่อ วงกลมใหญ่พับออกได้ และโถยาข้างรากกับใบไม้",
            "ภาพด้านบนสุด อักษรลอกจากหน้าสมุนไพรจริงทีละเส้น ส่วนต้นไม้วาดด้วยกฎกับการทอยลูกเต๋า แตะภาพเพื่อดูหน้าอื่น",
        ],

        "map_kick": "227 หน้าที่มีข้อความ",
        "map_h": "แผนที่ของเล่ม",
        "map_p": [
            "แต่ละช่องคือหน้าที่มีตัวเขียน เรียงตามเล่ม แถบสีบอกปริมาณข้อความ ระบายสีตามชนิดภาพ ตามสองสำเนียงที่เพรสคอตต์ เคอร์เรียร์ พบในปี 1976 หรือตามผู้เขียนห้าคนที่ลิซา เฟกิน เดวิส พบในปี 2020 สำเนียงและผู้เขียนตรงกับหมวดของเล่ม คนทำหนังสือเล่มนี้ไม่ได้เขียนทั้งเล่มแบบเดียวกัน",
        ],
        "map_modes": ["หมวด", "ภาษาของเคอร์เรียร์", "ผู้เขียน"],
        "map_page": "บรรทัดแรก ๆ ของหน้าที่เลือก วาดด้วยลายเส้น",
        "map_note": "แตะช่องเพื่อดูบรรทัดแรก ๆ เลขโฟลิโอบอกแผ่นและด้าน f1r คือด้านหน้าของแผ่นที่ 1 f1v คือด้านหลัง หมวด ภาษา และผู้เขียน มาจากหัวหน้าในไฟล์ถอดอักษรของเรอเน ซันเดอร์แบร์เคิน",

        "own_kick": "ที่มา",
        "own_h": "เจ้าของ",
        "own_p": [
            "เรื่องของเล่มนี้เริ่มที่ปรากราวปี 1600 และส่งต่อมาถึงเราผ่านจดหมาย ลายเซ็น และการซื้อขาย",
        ],
        "hist": [
            ("1599?", "จดหมายของมาร์ซีเล่าว่าจักรพรรดิรูดอล์ฟที่ 2 แห่งจักรวรรดิโรมันอันศักดิ์สิทธิ์จ่ายไป 600 ดูกัต ปี 2022 สเตฟาน กูซี พบว่ารูดอล์ฟซื้อหนังสือจากคาร์ล วีเดอมันน์ในปี 1599 ราคา 600 ฟลอริน น่าจะเป็นการซื้อครั้งนี้ รูดอล์ฟสะสมของแปลกและเลี้ยงนักเล่นแร่แปรธาตุ"),
            ("1608+", "ยาโคบัส ฮอร์ชิตสกี เด เตเปเนตส์ นักเคมีของรูดอล์ฟ เซ็นชื่อไว้ท้ายหน้าแรก เขาได้บรรดาศักดิ์ เด เตเปเนตส์ ในปี 1608 จึงเซ็นหลังจากนั้น ลายเซ็นจางหายไป วอยนิชใช้สารเคมีทำให้กลับมาราวปี 1914 และอ่านได้ใต้แสงอัลตราไวโอเลต"),
            ("1639", "จอร์จ บาเรสช์ นักเล่นแร่แปรธาตุในปราก เขียนถึงอธานาเซียส คิรเชอร์ นักวิชาการเยสุอิตในโรม ผู้อ้างว่าอ่านอักษรภาพอียิปต์ออก เพื่อขอความช่วยเหลือ จดหมายนี้เป็นการเอ่ยถึงหนังสือที่เก่าที่สุดที่แน่นอน"),
            ("1665", "โยฮันเนส มาคัส มาร์ซี อธิการมหาวิทยาลัยปราก ได้รับมรดกหนังสือ แล้วส่งไปให้คิรเชอร์พร้อมจดหมาย จดหมายนั้นยังอยู่กับหนังสือ มาร์ซีน่าจะเป็นคนเขียนแถวอักษรที่ถูกลบในขอบหน้าแรก ความพยายามทำกุญแจถอดรหัสที่เก่าที่สุดที่รู้"),
            ("1912", "วิลฟริด วอยนิช พ่อค้าหนังสือหายาก ซื้อจากคณะเยสุอิตใกล้กรุงโรม พร้อมหนังสืออื่นอีกลังหนึ่ง และใช้ชีวิตที่เหลือหาคนอ่านให้ออก"),
            ("1961", "วอยนิชเสียชีวิตปี 1930 เอเธล ภรรยาม่ายเสียชีวิตปี 1960 แอนน์ นิลล์ ทายาท ขายให้ฮันส์ พี. เคราส์ พ่อค้าหนังสือ ราคา 24,500 ดอลลาร์ เคราส์หาคนซื้อต่อไม่ได้"),
            ("1969", "เคราส์ยกให้มหาวิทยาลัยเยล ห้องสมุดไบเนคกีเปิดให้ดูทุกหน้าออนไลน์ฟรี"),
        ],

        "date_kick": "คาร์บอนกัมมันตรังสี",
        "date_h": "ใครเขียนได้บ้าง",
        "date_p": [
            "ปี 2009 ทีมจากมหาวิทยาลัยแอริโซนาตัดชิ้นเล็ก ๆ สี่ชิ้นจากสี่แผ่น แล้วหาอายุจากคาร์บอน ลูกวัวตายระหว่างปี 1404 ถึง 1438 การวิเคราะห์เคมีของหมึกและสีพบว่าเข้ากับยุคนั้น แต่หมึกหาอายุได้ไม่แม่นเท่าแผ่นหนัง",
            "แผ่นหนังเปล่าอาจวางบนชั้นหลายปีก่อนมีคนเขียน เลื่อนเวลาบนชั้นแล้วดูว่าผู้ต้องสงสัยคนไหนเป็นไปได้ โรเจอร์ เบคอน ตัวเก็งอยู่หลายสิบปี ตายก่อนลูกวัวเกิดกว่าร้อยปี",
        ],
        "d_wait": "ปีที่แผ่นหนังเปล่ารออยู่",
        "years": "ปี",
        "vellum_band": "แผ่นหนัง 1404–1438",
        "date_note": "สีเขียวแปลว่าคนนั้นมีชีวิตอยู่ช่วงที่แผ่นหนังยังใช้ได้ คนปลอมที่ใช้แผ่นหนังเก่าต้องหาให้ได้มาก ราว 240 หน้าที่เข้าชุดกัน ช่วงอายุปัดเศษ",

        "gl_kick": "ขั้นแรก จดให้ได้ก่อน",
        "gl_h": "อักษร",
        "gl_p": [
            "ก่อนนับอะไรได้ ต้องตัดสินก่อนว่าตัวอักษรคืออะไร ขีดม้วนนี้เป็นหางหรือเป็นตัวใหม่ วงสองวงที่ต่อกันข้างบนเป็นหนึ่งตัวหรือสองตัว คนอ่านแต่ละคนตอบไม่เหมือนกัน ผลนับจึงต่างกัน",
            "งานส่วนใหญ่วันนี้ใช้ EVA หรืออักษรวอยนิชแบบยุโรป ที่เรอเน ซันเดอร์แบร์เคิน กับกาบรีเอล ลันดีนี วางไว้ในปี 1997–98 EVA ให้อักษรละตินแทนกลุ่มเส้นปากกาแต่ละแบบ เพื่อให้คอมพิวเตอร์เก็บได้ อักษร EVA เป็นป้ายชื่อ ไม่ใช่เสียง <i>daiin</i> คือวิธีสะกดคำบนแป้นพิมพ์ ไม่ใช่วิธีที่ใครเคยออกเสียง",
            "แตะอักษร แถบบอกว่ามันอยู่ตรงไหนของคำ บางตัวอยู่ที่เดิมเสมอ เหมือน <i>q</i> ในภาษาอังกฤษที่มาก่อน <i>u</i>",
        ],
        "g_where": "อักษรอยู่ตรงไหนของคำ",
        "count_h": "ตัวเดียวหรือสองตัว",
        "count_p": [
            "EVA เขียนอักษรรูปม้านั่งเป็น <i>ch</i> สองตัว ถ้านับเป็นอักษรเดียว ตัวเลขก็ขยับ เอนโทรปีอันดับสอง h2 วัดว่าอักษรหนึ่งทายตัวถัดไปได้ดีแค่ไหน หัวข้อถัดไปอธิบาย",
        ],
        "u_eva": "นับตามอักษร EVA", "u_glyph": "นับ ch, sh, ckh เป็นอักษรเดียว",
        "u_letters": "อักษรที่ต่างกัน", "u_len": "อักษรต่อคำ",
        "name_h": "ชื่อคุณในอักษรวอยนิช",
        "name_p": "พิมพ์ชื่อเป็นอักษรโรมัน แต่ละตัวกลายเป็นอักษรวอยนิชตามตารางที่เราตั้งขึ้นเองสำหรับของเล่นรหัสด้านล่าง เป็นชุดแต่งตัว ไม่ใช่คำแปล",
        "name_default": "Annika",

        "cnt_kick": "ขั้นที่สอง นับ",
        "cnt_h": "นับดู",
        "cnt_p": [
            "อ่านไม่ออกก็ยังวัดได้ คนใช้การทดสอบชุดเดียวกับที่ใช้กับภาษาที่รู้จัก แล้วดูว่าตรงไหนเหมือนและตรงไหนแตก ข้างล่างใช้อย่างละ 12,000 คำ สองสำเนียงของต้นฉบับ ภาษาละตินจาก <i>คำสารภาพ</i> ของออกัสติน ภาษาอังกฤษจาก <i>ตำราสมุนไพร</i> ของคัลเพเพอร์ ปี 1652 และอักษรสุ่ม ของเล่นรหัสกับของปลอมด้านล่างเพิ่มชุดของตัวเองได้ ภาษาไทยไม่อยู่ในรายการ เพราะไม่เว้นวรรคระหว่างคำ การนับคำแบบนี้จึงใช้ไม่ได้",
        ],
        "b_zipf": "ความถี่ของคำ (ซิปฟ์)",
        "b_zipf_note": "เรียงคำตามจำนวนครั้งที่พบ แล้ววาดทั้งสองแกนแบบลอการิทึม ภาษามนุษย์ได้เส้นลาดลงราว −1 เส้นประ ต้นฉบับเป็นไปตามนั้น อักษรสุ่มไม่เป็น",
        "b_len": "ความยาวคำ",
        "b_len_note": "ความยาวคำของต้นฉบับกระจุกแน่นรอบห้าตัว คำสั้นมากหรือยาวมากมีน้อย ละตินกับอังกฤษกระจายกว้างกว่า",
        "b_h2": "h2 อักษรถัดไปทำให้แปลกใจแค่ไหน",
        "b_h2_note": "หน่วยเป็นบิต ยิ่งต่ำ ยิ่งทายอักษรถัดไปจากตัวก่อนหน้าได้ง่าย ภาษายุโรปอยู่ราว 3 ต้นฉบับอยู่ราว 2 อักษรของมันต่อกันตามนิสัยไม่กี่แบบ",
        "b_rep_h": "คำเดียวกันติดกันสองครั้ง",
        "b_rep_note": "ต่อพันคำ ละตินและอังกฤษไม่ค่อยซ้ำคำทันที ต้นฉบับซ้ำบ่อยกว่าราวสิบเท่า บางครั้งสามครั้งติด",
        "b_rank": "อันดับ", "b_count": "จำนวนครั้ง", "b_letters": "จำนวนอักษรในคำ", "b_share": "สัดส่วนของคำ",
        "b_types": "คำที่ต่างกัน", "b_mean": "อักษรต่อคำ", "b_rep": "ซ้ำต่อ 1,000", "b_top": "คำที่พบบ่อยสุด",
        "cnt_after": [
            "ข้อความเป็นไปตามกฎของซิปฟ์เหมือนภาษา แต่อักษรทายง่ายกว่าภาษายุโรปใด ๆ มาก และซ้ำตัวเองแบบที่ประโยคปกติไม่ค่อยทำ ทุกค่ายด้านล่างเริ่มจากสองข้อนี้",
            "ตัววัดอื่นชี้ไปทางเดียวกัน ปี 2013 มาร์เซโล มอนเตมูร์โร กับดาเมียน ซาเนตเต พบว่าบางคำกระจุกอยู่ในบางหมวด เหมือนคำหัวเรื่องในข้อความจริง อีกฝ่ายตอบว่าระบบผลิตข้อความไร้ความหมายก็ทำให้เกิดกระจุกได้",
        ],

        "gr_kick": "ขั้นที่สาม แยกคำเป็นชิ้น",
        "gr_h": "ไวยากรณ์ของคำ",
        "gr_p": [
            "คำวอยนิชประกอบจากชิ้นส่วนที่มาตามลำดับตายตัว <i>q</i> มาก่อนถ้ามี อักษรสูงที่เรียกว่า 'ตะแลงแกง' อยู่ช่วงหน้า <i>dy</i> <i>aiin</i> และ <i>ol</i> อยู่ท้าย ฮอร์เก สตอลฟี ในทศวรรษ 1990 และคนอื่นต่อมา เขียนเป็นไวยากรณ์แบบช่อง",
            "ของเราด้านล่างมีสิบเอ็ดช่อง หมุนเพื่อสร้างคำ หรือพิมพ์คำเพื่อดูการแยกชิ้น สัดส่วนคำในต้นฉบับที่เข้าช่องได้คำนวณสด",
        ],
        "gr_spin": "หมุน", "gr_try": "พิมพ์คำเป็นอักษร EVA",
        "gr_found": "พบในต้นฉบับ {n} ครั้ง", "gr_new": "ไม่พบในต้นฉบับ", "gr_nofit": "ไม่เข้าช่อง",
        "gr_tok_l": "คำในข้อความที่เข้าช่อง", "gr_ty_l": "คำที่ต่างกันที่เข้าช่อง",
        "gr_note": "ภาษาก็มีโครงสร้างคำ แต่หลวมกว่า ภาษาอังกฤษมีทั้ง <i>strengths</i> และ <i>a</i> ไวยากรณ์ช่องที่แน่นขนาดนี้เป็นเหตุหนึ่งที่หลายคนคิดว่าคำถูกผลิตด้วยระบบ จะเป็นรหัส ภาษาประดิษฐ์ หรือของปลอมก็ตาม",

        "rp_kick": "ขั้นที่สี่ อ่านแบบคนคัด",
        "rp_h": "คำซ้ำ",
        "rp_p": [
            "เลือกหน้า คำที่เคยปรากฏแล้วในหน้านั้นเป็นสีแดง คำที่ต่างจากคำก่อนหน้าแค่อักษรเดียว เช่น <i>qokedy</i> หลัง <i>qokeedy</i> หรือ <i>okedy</i> เป็นสีเหลือง",
            "ทอร์สเทน ทิมม์ สังเกตว่ามีคำจำนวนมากที่เกือบเหมือนคำข้างบน และร่วมกับอันเดรอัส ชินเนอร์ สร้างแบบจำลองในปี 2020 ผู้คัดไม่ได้คิดคำใหม่ แต่ลอกคำจากก่อนหน้าในหน้าเดียวกันแล้วเปลี่ยนอักษรหนึ่งสองตัว ลองเล่นได้ที่ของปลอม",
        ],
        "rp_pick": "หน้า",
        "rp_same": "เคยพบแล้วในหน้านี้", "rp_near": "ต่างกันอักษรเดียว", "rp_new": "ใหม่",
        "rp_note": "ข้อความปกติก็ซ้ำ เช่น <i>the</i>, <i>and</i>, <i>et</i> ให้ดูสัดส่วนสีเหลือง คำที่เกือบเหมือน ซึ่งภาษาปกติมีน้อยกว่ามาก",

        "ci_kick": "ทฤษฎีที่หนึ่ง",
        "ci_h": "รหัสลับ",
        "ci_p": [
            "บางทีหนังสือเล่าเรื่องธรรมดาในภาษาละติน อิตาลี หรือเยอรมัน ซ่อนด้วยรหัส อิตาลีต้นศตวรรษที่ 15 มีรหัสที่สลับอักษรเป็นสัญลักษณ์และเติมสัญลักษณ์ที่ไม่มีความหมาย นักถอดรหัสของสงครามโลกทั้งสองครั้งลองทุกวิธีที่รู้ ไม่มีวิธีไหนได้ผล",
            "พิมพ์ภาษาละตินแล้วเลือกวิธี ม้านั่งทดสอบในหัวข้อนับแสดงว่าแต่ละวิธีทำอะไรกับสถิติ บนงานของออกัสติน 12,000 คำ",
        ],
        "c_plain": "ข้อความธรรมดา (ละตินดีที่สุด)",
        "c_default": "herba haec nascitur in locis humidis et habet folia lata et radicem longam",
        "c_sub": "สลับทีละอักษร", "c_verb": "สะกดแต่ละอักษรเป็นพยางค์",
        "ci_how": [
            "<b>สลับ</b> แต่ละอักษรกลายเป็นอักษรวอยนิชหนึ่งตัว คำยาวเท่าเดิม รูปแบบเดิม h2 ยังใกล้ละติน",
            "<b>พยางค์</b> รหัสแบบเยิ่นเย้อ แต่ละอักษรกลายเป็นชิ้นสั้น เช่น <i>ok</i> หรือ <i>aiin</i> แล้วตัดชิ้นเป็นคำใหม่ h2 ลดลงใกล้ต้นฉบับ แต่คำศัพท์หดลง",
        ],
        "c_bench": "บนงานของออกัสติน 12,000 คำ",
        "ci_after": [
            "การสลับอักษรอธิบาย h2 ที่ต่ำไม่ได้ เพราะการสลับเฉย ๆ เก็บแบบแผนของภาษาเดิมไว้ ทีมของฟรีดแมนก็สังเกตเห็น รหัสแบบเยิ่นเย้อเข้าใกล้กว่า ปี 2025 ไมเคิล เกรชโก สร้างรหัสแบบนี้จากลูกเต๋ากับไพ่ เครื่องมือที่ชาวอิตาลีศตวรรษที่ 15 มีได้ และแสดงว่าเข้ากับสถิติของต้นฉบับได้หลายข้อ ยังไม่มีใครพบรหัสที่แปลงข้อความกลับเป็นภาษาได้",
        ],

        "hx_kick": "ทฤษฎีที่สอง",
        "hx_h": "ของปลอม",
        "hx_p": [
            "บางทีไม่มีสารอะไรเลย มีคนทำหนังสือประหลาดไว้ขาย วิลฟริด วอยนิชเองเคยถูกสงสัย แต่แผ่นหนัง หมึก และจดหมายปี 1665 ตัดเขาออก เอ็ดเวิร์ด เคลลีย์ นักต้มตุ๋นในราชสำนักรูดอล์ฟ เคยเป็นตัวเก็ง คำถามจึงกลายเป็นว่า คนยุคนั้นผลิตข้อความ 240 หน้าที่สม่ำเสมอขนาดนี้โดยไม่มีความหมายได้ไหม",
            "ปี 2004 กอร์ดอน รักก์ แสดงวิธีหนึ่ง เติมตารางด้วยชิ้นส่วนคำ ต้น กลาง ท้าย วางแผ่นที่เจาะสามรูทับ ทุกตำแหน่งที่วางได้หนึ่งคำ เลื่อนแผ่นแล้วทำต่อ",
        ],
        "hx_grille": "ตะแกรงของรักก์ ตารางชิ้นส่วนคำ รูของแผ่นเป็นสีทอง",
        "hx_word": "มองผ่านรู:",
        "hx_step": "เลื่อนแผ่น", "hx_card": "เปลี่ยนแผ่น", "hx_new": "ตารางใหม่", "hx_run": "สร้าง 12,000 คำใส่ม้านั่งทดสอบ",
        "hx_grille_p": [
            "ตารางของเราเล็กและชิ้นส่วนเป็นของเราเอง ไม่ใช่ของรักก์ ข้อสรุปของเขายังใช้ได้ คำจากตะแกรงมีโครงสร้างแน่นและ h2 ต่ำแบบต้นฉบับ ตารางเล็กทำให้คำศัพท์น้อยเกินและเส้นซิปฟ์ไม่ตรง รักก์ใช้ตารางใหญ่กว่าและแผ่นหลายแบบกว่า",
        ],
        "gr_ran": "เพิ่มในม้านั่งทดสอบแล้ว คำที่ต่างกัน {types} คำ h2 {h2} ความชันซิปฟ์ {z}",
        "sc_h": "ลอกตัวเอง",
        "sc_p": [
            "ผู้คัดของทิมม์กับชินเนอร์เริ่มจากบรรทัดหนึ่งในต้นฉบับ แล้วเขียนคำใหม่ทีละคำโดยลอกคำจากบรรทัดบนหรือใกล้ ๆ แล้วเปลี่ยนนิดหน่อย <i>k</i> เป็น <i>t</i> เติม <i>e</i> หรือเปลี่ยนหางคำ คำล่าสุดเป็นสีแดง เส้นประชี้ไปยังคำที่มันคล้ายที่สุด",
        ],
        "sc_play": "เขียนหน้าใหม่",
        "sc_after": [
            "ของเราเป็นภาพร่างหยาบของวิธีเขา ตัวเลขเพี้ยนจากต้นฉบับ ของเขาปรับมาแล้วและเข้ากับต้นฉบับได้มากกว่า ทั้งตะแกรงและการลอกไม่ได้พิสูจน์ว่าข้อความไร้ความหมาย มันแสดงว่าความไร้ความหมายอธิบายสถิติได้ดีพอ ๆ กับรหัส",
        ],

        "lg_kick": "ทฤษฎีที่สาม",
        "lg_h": "ภาษาจริง",
        "lg_p": [
            "บางทีเป็นภาษาจริงเขียนด้วยอักษรใหม่ สำเนียงที่สูญไป ภาษาจากแดนไกลที่นักเดินทางจดไว้ หรือภาษาที่ตัดคำให้สั้นจนหางคำซ้ำกัน กฎของซิปฟ์ คำที่กระจุกตามหมวด และการที่ป้ายข้างภาพต่างจากข้อความต่อเนื่อง ล้วนเข้ากับภาษาได้",
            "h2 ที่ต่ำคือปัญหา มันเข้ากับภาษาได้ก็ต่อเมื่อระบบอักษรทำงานต่างจากของเรา เช่น อักษรบางตัวเป็นแค่ส่วนของตัวอักษร หรือ <i>aiin</i> เป็นเสียงเดียวที่เขียนด้วยสี่เส้น การเลือกของ EVA ว่าอะไรนับเป็นอักษรจึงสำคัญ อย่างที่เห็นในหัวข้ออักษร",
            "คำอ่านที่ประกาศมาทุกครั้งตกการทดสอบข้อใดข้อหนึ่งในสองข้อ วิธีต้องให้คำตอบเดียวกันกับทุกคนที่ทำตาม และต้องอ่านทั้งบรรทัดออกมาเป็นประโยคที่ถูกไวยากรณ์ คำอ่านบางส่วนของป้ายไม่กี่ป้าย อย่างของสตีเฟน แบกซ์ ผ่านข้อแรกสำหรับคำไม่กี่คำ และยังไปไม่ถึงข้อสอง",
            "ปี 2026 คอลิน เลย์ฟิลด์ กับลิซา เฟกิน เดวิส ใช้การวิเคราะห์ความหมายแฝง ตรวจว่าข้อความที่อยู่ติดกันใช้คำร่วมกันแบบเรื่องเดียวกันไหม และพบว่าข้อความไหลแบบข้อความที่รู้จัก อีกบทความเสนอว่าเล่มนี้เริ่มจากแผ่นพับแยกกัน อ่านตามลำดับ แล้วถูกเย็บเล่มผิดลำดับภายหลัง และพยายามเรียงกลับ",
        ],

        "pc_kick": "อ่านโดยไม่ใช้คำ",
        "pc_h": "ภาพ",
        "pc_p": [
            "ภาพเป็นส่วนเดียวที่ใครก็ดูได้ นักพฤกษศาสตร์พยายามระบุพืชมาร้อยปี บางต้นดูเหมือนไวโอเล็ต เฟิร์น บัว หรือทานตะวัน หลายต้นไม่เหมือนอะไรเลย บางต้นเอารากของพืชหนึ่งมาต่อกับใบของอีกพืช",
            "หน้าจักรราศีสิบหน้ามีชื่อเดือน มีนาคมถึงธันวาคม เขียนด้วยอักษรละตินโดยมือที่มาทีหลัง เช่น <i>mars</i> <i>aberil</i> <i>may</i> <i>augst</i> เป็นคำไม่กี่คำในเล่มที่ใครก็อ่านออก เรอเน ซันเดอร์แบร์เคิน อ่านว่าเป็นภาษาฝรั่งเศสตอนเหนือ ใกล้กับชื่อเดือนบนแอสโทรเลบจากแคว้นปีการ์ดี ครั้งหนึ่งอาจมีคนแถวนั้นถือมันไว้",
        ],
        "pc_after": [
            "ปี 2024 คีแกน บรูเออร์ กับมิเชล ลูอิส อ่านภาพผู้หญิง บ่อน้ำ และแผนภาพหมุน ว่าเป็นการแพทย์ศตวรรษที่ 15 เรื่องเพศและการคลอด ซึ่งผู้เขียนยุคนั้นบางครั้งเข้ารหัสไว้ เช่นเดียวกับการอ่านภาพทุกแบบ มันบอกว่าหนังสืออาจว่าด้วยเรื่องอะไร โดยไม่ได้อ่านคำใดเลย",
        ],

        "cl_kick": "หนึ่งศตวรรษของคำตอบ",
        "cl_h": "คำตอบที่ประกาศ",
        "cl_p": [
            "แทบทุกปีมีคนประกาศว่าไขได้แล้ว นี่คือรายที่คนสนใจมากที่สุด แถบแดง: ผู้เชี่ยวชาญไม่รับ · แถบเหลือง: ยังถกเถียง · แถบเขียว: วิธีสร้างข้อความแบบวอยนิช ไม่ใช่คำแปล",
        ],
        "cl_after": [
            "ห้องสมุดไบเนคกีได้รับอีเมลอ้างว่าไขได้บ่อยจนภัณฑารักษ์มีคำตอบเตรียมไว้ ลิซา เฟกิน เดวิส ผู้อ่านมาแล้วหลายราย ถามสองข้อกับทุกราย อ่านได้ทั้งประโยคไหม และถ้าคนอื่นทำตามกฎเดียวกันจะได้คำเดียวกันไหม",
        ],

        "words_h": "คำศัพท์",
        "src_h": "แหล่งที่มา",
        "src_p": ["ข้อความถอดอักษรในหน้านี้คือไฟล์ ZL ฉบับ 3b ของเรอเน ซันเดอร์แบร์เคิน จาก voynich.nu ให้ใช้แบบ CC0 ตัวอย่างละตินและอังกฤษมาจากโปรเจกต์กูเทนเบิร์ก ตัวเลขทุกตัวในหน้านี้คำนวณในเบราว์เซอร์ของคุณจากไฟล์เหล่านั้น"],
        "foot": "ข้อความ CC BY 4.0, NaNoBotCo โค้ด MIT ภาพจากวิกิมีเดียคอมมอนส์ ให้เครดิตใต้ภาพ",
        "pic": {
            "f1r": "f1r หน้าแรก ลายเซ็นจาง ๆ อยู่ด้านล่าง",
            "herbal": "f2r หน้าสมุนไพร พืชหนึ่งต้นจากรากถึงดอก มีข้อความล้อมรอบ แบกซ์อ่านป้ายว่าเซนทอรี",
            "rosettes": "ส่วนหนึ่งของหน้าพับวงกลม (f85v–f86r) เก้าวงต่อกันด้วยทางเดิน",
            "f116v": "f116v หน้าสุดท้าย ไม่กี่บรรทัดที่ปนคำคล้ายละติน เยอรมัน และอักษรวอยนิช ข้อความที่ถกเถียงกันมากที่สุดในเล่ม",
            "voynich": "วิลฟริด วอยนิช ท่ามกลางหนังสือในร้านที่โซโหสแควร์ ลอนดอน",  # stylecheck: allow — สแควร์ is 'Square', not ควร
            "zodiac": "f70v2 ราศีมีน มีชื่อเดือน <i>mars</i> เป็นอักษรละติน",
            "balneo": "f75r ผู้หญิงในบ่อน้ำที่ต่อกันด้วยท่อ",
            "pharma": "f99r หน้าตำรายา โถ ราก และใบไม้พร้อมป้าย",
        },
        "js": {
            "sections": SECTIONS_TH,
            "words_unit": "คำ", "lang_a": "ภาษา A", "lang_b": "ภาษา B", "unknown": "ไม่ระบุ", "hand": "ผู้เขียน",
            "years": "ปี", "vellum_band": "แผ่นหนัง 1404–1438",
            "cands": [["โรเจอร์ เบคอน", 1219, 1292], ["เลออน บัตติสตา อัลแบร์ตี", 1404, 1472], ["โยฮันเนส ฮาร์ทลีบ", 1410, 1468], ["อันโตนีโอ อาเวร์ลีโน", 1400, 1469], ["จอห์น ดี", 1527, 1609], ["เอ็ดเวิร์ด เคลลีย์", 1555, 1597], ["รูดอล์ฟที่ 2", 1552, 1612], ["วิลฟริด วอยนิช", 1865, 1930]],
            "g_pos": ["ต้น", "กลาง", "ท้าย"],
            "g_note": {
                "q": "<i>q</i> แทบทุกครั้งขึ้นต้นคำ และตามด้วย <i>o</i> เป็น <i>qo</i> เช่น <i>qokeedy</i>",
                "k": "<i>k</i> <i>t</i> <i>p</i> <i>f</i> คืออักษรสูงที่เรียกว่าตะแลงแกง <i>p</i> กับ <i>f</i> มักอยู่บรรทัดแรกของย่อหน้า",
                "t": "อักษรตะแลงแกง แบบม้านั่ง เช่น <i>cth</i> ยืนคร่อม <i>ch</i>",
                "p": "ตะแลงแกงที่มีเส้นบนยาว พบบ่อยในบรรทัดแรกของย่อหน้า",
                "f": "ตะแลงแกงที่หายากที่สุด ส่วนใหญ่อยู่บรรทัดแรก",
                "n": "แทบทุกครั้งอยู่ท้ายคำ หลัง <i>i</i> เรียงกัน เช่น <i>aiin</i> <i>daiin</i>",
                "m": "แทบทุกครั้งอยู่ท้ายคำ และบ่อยครั้งท้ายบรรทัด",
                "i": "มาเป็นชุดหนึ่งถึงสามตัว แล้วตามด้วย <i>n</i> หรือ <i>r</i> เช่น <i>ain</i> <i>aiin</i> <i>aiiin</i>",
                "y": "ส่วนใหญ่อยู่ท้ายคำ เช่น <i>dy</i> <i>chy</i> <i>qokeedy</i>",
                "ch": "รูปม้านั่ง EVA เขียนเป็นสองตัว แต่ปากกาลากเป็นรูปเดียว",
                "o": "อักษรที่พบบ่อยที่สุด อยู่ตรงไหนของคำก็ได้",
                "e": "มักมาสองหรือสามตัว เช่น <i>chee</i> <i>qokeeey</i>",
                "d": "มักนำหน้า <i>y</i> หรือ <i>aiin</i> เช่น <i>dy</i> <i>daiin</i> คำที่พบบ่อยที่สุด",
            },
            "corp": {"va": "วอยนิช A", "vb": "วอยนิช B", "la": "ละติน", "en": "อังกฤษ", "sub": "ละติน สลับอักษร", "verb": "ละติน รหัสพยางค์", "gr": "ตะแกรง", "sc": "ลอกตัวเอง", "rnd": "อักษรสุ่ม"},
            "b_rank": "อันดับ (ลอก)", "b_count": "จำนวนครั้ง (ลอก)", "b_letters": "จำนวนอักษรในคำ", "b_share": "สัดส่วนของคำ",
            "b_types": "คำที่ต่างกัน", "b_mean": "อักษรต่อคำ", "b_rep": "ซ้ำต่อ 1,000", "b_top": "คำที่พบบ่อยสุด",
            "gr_found": "พบในต้นฉบับ {n} ครั้ง", "gr_new": "ไม่พบในต้นฉบับ", "gr_nofit": "ไม่เข้าช่อง",
            "gr_ran": "เพิ่มในม้านั่งทดสอบแล้ว คำที่ต่างกัน {types} คำ h2 {h2} ความชันซิปฟ์ {z}",
        },
    },
}

WORDS = [
    ("Vellum", "แผ่นหนังลูกวัว", "Calfskin scraped thin and dried flat to write on. Its carbon gives the date the calf died.", "หนังลูกวัวขูดบางแล้วตากให้เรียบไว้เขียน คาร์บอนในหนังบอกปีที่ลูกวัวตาย"),
    ("Folio", "โฟลิโอ", "One leaf of the book. r (recto) is the front, v (verso) the back: f1r, f1v.", "แผ่นหนึ่งของหนังสือ r คือด้านหน้า v คือด้านหลัง เช่น f1r f1v"),
    ("EVA", "อักษร EVA", "European Voynich Alphabet: Latin letters standing for Voynich pen strokes, so a computer can store the text. A label, not a sound.", "อักษรวอยนิชแบบยุโรป ใช้อักษรละตินแทนเส้นปากกาวอยนิช เพื่อให้คอมพิวเตอร์เก็บข้อความได้ เป็นป้ายชื่อ ไม่ใช่เสียง"),
    ("Transliteration", "การถอดอักษร", "Writing one script in another letter by letter, without translating. The ZL file is a transliteration of every page into EVA.", "การเขียนอักษรหนึ่งด้วยอีกอักษรทีละตัว โดยไม่แปล ไฟล์ ZL คือการถอดทุกหน้าเป็น EVA"),
    ("Gallows", "ตะแลงแกง", "The four tall Voynich letters, EVA k, t, p, f, named for their shape.", "อักษรวอยนิชสูงสี่ตัว EVA k t p f ตั้งชื่อตามรูปร่าง"),
    ("Currier A and B", "ภาษา A และ B ของเคอร์เรียร์", "Two dialects of the text Prescott Currier found in 1976: different common words, different spellings, matching different sections.", "สองสำเนียงของข้อความที่เพรสคอตต์ เคอร์เรียร์ พบในปี 1976 คำที่พบบ่อยต่างกัน การสะกดต่างกัน ตรงกับคนละหมวด"),
    ("Zipf's law", "กฎของซิปฟ์", "In a language the commonest word appears about twice as often as the second, three times as often as the third, and so on.", "ในภาษา คำที่พบบ่อยที่สุดพบราวสองเท่าของอันดับสอง สามเท่าของอันดับสาม และต่อไปเรื่อย ๆ"),
    ("Entropy, h2", "เอนโทรปี h2", "A measure in bits of how unpredictable the next letter is once you know the one before it. Lower means more predictable.", "ตัววัดเป็นบิตว่าอักษรถัดไปทายยากแค่ไหน เมื่อรู้ตัวก่อนหน้าแล้ว ยิ่งต่ำยิ่งทายง่าย"),
    ("Verbose cipher", "รหัสเยิ่นเย้อ", "A cipher that writes each plain letter as several cipher symbols, so the text grows longer and more repetitive.", "รหัสที่เขียนอักษรธรรมดาตัวหนึ่งเป็นสัญลักษณ์หลายตัว ข้อความจึงยาวขึ้นและซ้ำมากขึ้น"),
    ("Cardan grille", "ตะแกรงคาร์ดาโน", "A card with holes laid over a sheet to pick out letters or pieces. Named for Gerolamo Cardano, who described it in 1550.", "แผ่นเจาะรูวางทับกระดาษเพื่อเลือกอักษรหรือชิ้นส่วน ตั้งชื่อตามเจโรลาโม การ์ดาโน ผู้บรรยายไว้ในปี 1550"),
    ("Radiocarbon dating", "การหาอายุด้วยคาร์บอน", "Living things take in carbon-14, which decays at a known rate after death. Measuring what is left gives the date of death.", "สิ่งมีชีวิตรับคาร์บอน-14 เข้าไป หลังตายมันสลายในอัตราที่รู้ วัดส่วนที่เหลือก็ได้ปีที่ตาย"),
    ("A priori language", "ภาษาประดิษฐ์แบบอะไพรออริ", "A made-up language whose words are built from a classification of ideas, not borrowed from real languages. Friedman's theory.", "ภาษาที่สร้างขึ้นโดยคำประกอบจากการจัดหมวดความคิด ไม่ได้ยืมจากภาษาจริง ทฤษฎีของฟรีดแมน"),
]

SOURCES = [
    ("Beinecke Library: Voynich Manuscript, full digital copy", "https://collections.library.yale.edu/catalog/2002046"),
    ("René Zandbergen, voynich.nu: description, history, transliterations (CC0)", "https://www.voynich.nu/"),
    ("voynich.nu: the radiocarbon dating and the McCrone ink report", "https://www.voynich.nu/extra/carbon.html"),
    ("voynich.nu: the month names and other writing in Latin letters", "https://www.voynich.nu/writing.html"),
    ("Stefan Guzy, The Purchase of the Voynich Manuscript by Rudolf II (2022)", "https://ceur-ws.org/Vol-3313/paper16.pdf"),
    ("Lisa Fagin Davis, How Many Glyphs and How Many Scribes? Manuscript Studies 5.1 (2020)", "https://doi.org/10.1353/mns.2020.0011"),
    ("Lisa Fagin Davis, Multispectral imaging and the Voynich Manuscript (2024)", "https://manuscriptroadtrip.wordpress.com/2024/09/08/multispectral-imaging-and-the-voynich-manuscript/"),
    ("Prescott Currier's papers, at voynich.nu", "https://www.voynich.nu/a1_intro.html"),
    ("John Manly, Roger Bacon and the Voynich MS, Speculum 6 (1931)", "https://doi.org/10.2307/2848508"),
    ("Jorge Stolfi, A grammar for Voynichese words (2000)", "https://www.ic.unicamp.br/~stolfi/voynich/00-06-07-word-grammar/"),
    ("Bowern & Lindemann, The Linguistics of the Voynich Manuscript, Annual Review of Linguistics 7 (2021)", "https://doi.org/10.1146/annurev-linguistics-011619-030613"),
    ("Montemurro & Zanette, Keywords and Co-Occurrence Patterns in the Voynich Manuscript, PLOS ONE (2013)", "https://doi.org/10.1371/journal.pone.0066344"),
    ("Gordon Rugg, An Elegant Hoax? Cryptologia 28 (2004)", "https://doi.org/10.1080/0161-110491892755"),
    ("Timm & Schinner, A possible generating algorithm of the Voynich manuscript, Cryptologia 44 (2020)", "https://doi.org/10.1080/01611194.2019.1596999"),
    ("Stephen Bax, A proposed provisional partial decoding of the Voynich script (2014)", "https://stephenbax.net/wp-content/uploads/2014/01/Voynich-a-provisional-partial-decoding-BAX.pdf"),
    ("Hauer & Kondrak, Decoding Anagrammed Texts Written in an Unknown Language and Script, TACL 4 (2016)", "https://doi.org/10.1162/tacl_a_00084"),
    ("Gerard Cheshire, The Language and Writing System of MS408 (Voynich) Explained, Romance Studies 37 (2019)", "https://doi.org/10.1080/02639904.2019.1599566"),
    ("Brewer & Lewis, The Voynich Manuscript, Dr Johannes Hartlieb and the Encipherment of Women's Secrets, Social History of Medicine 37 (2024)", "https://doi.org/10.1093/shm/hkad099"),
    ("Michael Greshko, The Naibbe cipher, Cryptologia (2025)", "https://doi.org/10.1080/01611194.2025.2566408"),
    ("Layfield & Davis, Latent Semantic Analysis and the Voynich Manuscript, Digital Humanities Quarterly (2026)", "https://doi.org/10.63744/2ezxpskcezq4"),
    ("Layfield & Davis, Singulion Structure and the Voynich Manuscript, Digital Medievalist 19 (2026)", "https://doi.org/10.4000/16k0a"),
    ("Project Gutenberg: Augustine, Confessiones (33849); Culpeper, The Complete Herbal (49513)", "https://www.gutenberg.org/ebooks/33849"),
]
